"""init

Revision ID: 0001_init
Revises:
Create Date: 2026-06-30 23:33:45.189880
"""

from alembic import op
import sqlalchemy as sa

revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("meta", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("is_html", sa.Boolean(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_templates_slug"), "email_templates", ["slug"], unique=True
    )
    op.create_table(
        "lua_scripts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lua_scripts_slug"), "lua_scripts", ["slug"], unique=True)
    op.create_table(
        "oauth_cfg",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret_enc", sa.Text(), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=True),
        sa.Column("authorize_url", sa.String(length=512), nullable=True),
        sa.Column("token_url", sa.String(length=512), nullable=True),
        sa.Column("userinfo_url", sa.String(length=512), nullable=True),
        sa.Column("jwks_uri", sa.String(length=512), nullable=True),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column("extra", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_cfg_slug"), "oauth_cfg", ["slug"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("perms", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "settings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "svc_catalogs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("icon", sa.String(length=512), nullable=True),
        sa.Column("sort", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["svc_catalogs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_svc_catalogs_parent_id"), "svc_catalogs", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_svc_catalogs_slug"), "svc_catalogs", ["slug"], unique=True)
    op.create_table(
        "system_media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("backend", sa.String(length=8), nullable=False),
        sa.Column("mime", sa.String(length=128), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("meta", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_media_owner_id"), "system_media", ["owner_id"], unique=False
    )
    op.create_table(
        "triggers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("cond", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_triggers_event"), "triggers", ["event"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("pass_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "bonus_balance",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_email"), "accounts", ["email"], unique=True)
    op.create_index(op.f("ix_accounts_login"), "accounts", ["login"], unique=True)
    op.create_index(op.f("ix_accounts_role_id"), "accounts", ["role_id"], unique=False)
    op.create_table(
        "pay_providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("secrets_enc", sa.Text(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("init_script_id", sa.Integer(), nullable=True),
        sa.Column("cb_script_id", sa.Integer(), nullable=True),
        sa.Column("extra", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cb_script_id"], ["lua_scripts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["init_script_id"], ["lua_scripts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pay_providers_cb_script_id"),
        "pay_providers",
        ["cb_script_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pay_providers_init_script_id"),
        "pay_providers",
        ["init_script_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pay_providers_slug"), "pay_providers", ["slug"], unique=True
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("catalog_id", sa.Integer(), nullable=True),
        sa.Column(
            "price",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("delivery", sa.String(length=8), nullable=False),
        sa.Column("lua_script_id", sa.Integer(), nullable=True),
        sa.Column("params", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column(
            "settings", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("image", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_id"], ["svc_catalogs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lua_script_id"], ["lua_scripts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_services_catalog_id"), "services", ["catalog_id"], unique=False
    )
    op.create_index(
        op.f("ix_services_lua_script_id"), "services", ["lua_script_id"], unique=False
    )
    op.create_index(op.f("ix_services_slug"), "services", ["slug"], unique=True)
    op.create_table(
        "digi_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_digi_keys_service_id"), "digi_keys", ["service_id"], unique=False
    )
    op.create_table(
        "oauth_conns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("raw", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "subject", name="uq_oauth_provider_subject"),
    )
    op.create_index(
        op.f("ix_oauth_conns_account_id"), "oauth_conns", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_conns_provider"), "oauth_conns", ["provider"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "public_data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "private_data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("target", sa.String(length=16), nullable=False),
        sa.Column("user_svc_id", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payments_account_id"), "payments", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_external_id"), "payments", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_provider"), "payments", ["provider"], unique=False
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(
        op.f("ix_payments_user_svc_id"), "payments", ["user_svc_id"], unique=False
    )
    op.create_table(
        "promo_catalogs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "value",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("discount_type", sa.String(length=8), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("per_user", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "settings", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "conditions", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["promo_catalogs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promo_catalogs_parent_id"),
        "promo_catalogs",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promo_catalogs_slug"), "promo_catalogs", ["slug"], unique=True
    )
    op.create_table(
        "user_services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "public_data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "private_data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "price",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "discount",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("params", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("digikey_id", sa.Integer(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_services_account_id"),
        "user_services",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_services_payment_id"),
        "user_services",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_services_service_id"),
        "user_services",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_services_status"), "user_services", ["status"], unique=False
    )
    op.create_table(
        "promocodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("catalog_id", sa.Integer(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("used_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_id"], ["promo_catalogs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promocodes_catalog_id"), "promocodes", ["catalog_id"], unique=False
    )
    op.create_index(op.f("ix_promocodes_code"), "promocodes", ["code"], unique=True)
    op.create_table(
        "promo_uses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("promocode_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["promocode_id"], ["promocodes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promo_uses_account_id"), "promo_uses", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_promo_uses_promocode_id"), "promo_uses", ["promocode_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_promo_uses_promocode_id"), table_name="promo_uses")
    op.drop_index(op.f("ix_promo_uses_account_id"), table_name="promo_uses")
    op.drop_table("promo_uses")
    op.drop_index(op.f("ix_promocodes_code"), table_name="promocodes")
    op.drop_index(op.f("ix_promocodes_catalog_id"), table_name="promocodes")
    op.drop_table("promocodes")
    op.drop_index(op.f("ix_user_services_status"), table_name="user_services")
    op.drop_index(op.f("ix_user_services_service_id"), table_name="user_services")
    op.drop_index(op.f("ix_user_services_payment_id"), table_name="user_services")
    op.drop_index(op.f("ix_user_services_account_id"), table_name="user_services")
    op.drop_table("user_services")
    op.drop_index(op.f("ix_promo_catalogs_slug"), table_name="promo_catalogs")
    op.drop_index(op.f("ix_promo_catalogs_parent_id"), table_name="promo_catalogs")
    op.drop_table("promo_catalogs")
    op.drop_index(op.f("ix_payments_user_svc_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider"), table_name="payments")
    op.drop_index(op.f("ix_payments_external_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_account_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_oauth_conns_provider"), table_name="oauth_conns")
    op.drop_index(op.f("ix_oauth_conns_account_id"), table_name="oauth_conns")
    op.drop_table("oauth_conns")
    op.drop_index(op.f("ix_digi_keys_service_id"), table_name="digi_keys")
    op.drop_table("digi_keys")
    op.drop_index(op.f("ix_services_slug"), table_name="services")
    op.drop_index(op.f("ix_services_lua_script_id"), table_name="services")
    op.drop_index(op.f("ix_services_catalog_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_pay_providers_slug"), table_name="pay_providers")
    op.drop_index(op.f("ix_pay_providers_init_script_id"), table_name="pay_providers")
    op.drop_index(op.f("ix_pay_providers_cb_script_id"), table_name="pay_providers")
    op.drop_table("pay_providers")
    op.drop_index(op.f("ix_accounts_role_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_login"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_email"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_triggers_event"), table_name="triggers")
    op.drop_table("triggers")
    op.drop_index(op.f("ix_system_media_owner_id"), table_name="system_media")
    op.drop_table("system_media")
    op.drop_index(op.f("ix_svc_catalogs_slug"), table_name="svc_catalogs")
    op.drop_index(op.f("ix_svc_catalogs_parent_id"), table_name="svc_catalogs")
    op.drop_table("svc_catalogs")
    op.drop_table("settings")
    op.drop_table("roles")
    op.drop_index(op.f("ix_oauth_cfg_slug"), table_name="oauth_cfg")
    op.drop_table("oauth_cfg")
    op.drop_index(op.f("ix_lua_scripts_slug"), table_name="lua_scripts")
    op.drop_table("lua_scripts")
    op.drop_index(op.f("ix_email_templates_slug"), table_name="email_templates")
    op.drop_table("email_templates")
    op.drop_table("api_logs")
    # ### end Alembic commands ###
